In [1]:
import sys
import scanpy as sc
import anndata
import pandas as pd
import numpy as np
import os

data_type = 'float32'

import matplotlib as mpl
from matplotlib import rcParams
import matplotlib.pyplot as plt
import seaborn as sns

# silence scanpy that prints a lot of warnings
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import GridSearchCV, KFold, train_test_split, ParameterGrid
from sklearn.metrics import make_scorer, accuracy_score
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
import pickle

import tqdm
from tqdm import tqdm

import xgboost
from xgboost import XGBClassifier


merged_features = pd.read_csv('../TPC_data.csv', index_col=0)

In [2]:
merged_features['age'].replace('21yr', 0, inplace=True)
merged_features['age'].replace('22yr', 0, inplace=True)
merged_features['age'].replace('30yr', 1, inplace=True)
merged_features['age'].replace('32yr', 1, inplace=True)
merged_features['age'].replace('33yr', 1, inplace=True)
merged_features['age'].replace('38yr', 1, inplace=True)
merged_features['age'].replace('40yr', 2, inplace=True)
merged_features['age'].replace('42yr', 2, inplace=True)
merged_features['age'].replace('43yr', 2, inplace=True)
merged_features['age'].replace('44yr', 2, inplace=True)
merged_features['age'].replace('46yr', 2, inplace=True)
merged_features['age'].replace('48yr', 2, inplace=True)
merged_features['age'].replace('52yr', 3, inplace=True)
merged_features['age'].replace('53yr', 3, inplace=True)
merged_features['age'].replace('55yr', 3, inplace=True)
merged_features['age'].replace('57yr', 3, inplace=True)
merged_features['age'].replace('59yr', 3, inplace=True)
merged_features['age'].replace('62yr', 4, inplace=True)
merged_features['age'].replace('64yr', 4, inplace=True)
merged_features['age'].replace('66yr', 4, inplace=True)
merged_features['age'].replace('67yr', 4, inplace=True)
merged_features['age'].replace('69yr', 4, inplace=True)

In [3]:
y = merged_features['age']

features = list(merged_features.columns)
features.remove('age')
features.remove('BMI')
X = merged_features[features]

# mutual_info

In [4]:
from sklearn.feature_selection import mutual_info_classif
X_mutual_info = mutual_info_classif(X, y, discrete_features= False)
X_mutual_info=list(X_mutual_info)
X_mutual_info

[0.0,
 0.0,
 0.016151322570979065,
 0.00021400566909779428,
 0.009457603999160735,
 0.0040811366210680156,
 0.0071288117234238335,
 0.0,
 0.003944191589385859,
 0.005180243987538802,
 0.002197955870444801,
 0.00669997790497856,
 0.0,
 0.0037122296748819394,
 0.012083018547999647,
 0.0,
 0.008025608598640765,
 0.0,
 0.0019948751020892885,
 0.009590239784536436,
 0.0001828793836224918,
 0.005222483037502723,
 0.005819580591444051,
 0.0063090571049131405,
 0.0,
 0.0,
 0.0016671976910673791,
 0.0,
 0.012100227124277385,
 0.009801367131852867,
 0.016157037270663643,
 0.004264189452626965,
 0.00282201779291702,
 0.011508764832734553,
 0.005644607356170006,
 0.006437485580632618,
 0.002529191765932026,
 0.0025052750271501445,
 0.003501669545379116,
 0.008848718784066012,
 0.0006399979023345992,
 0.0009481316823078956,
 0.0018953650080559825,
 0.0,
 0.0,
 0.0051167507847798,
 0.0018054167363108498,
 0.0,
 0.006436285905041306,
 0.006534272846129063,
 0.007852106500546352,
 0.00016262326464522303,
 0.00474538298295224,
 0.016417043836949752,
 0.00956499598769911,
 0.0,
 0.004650435547816745,
 0.030680128834082776,
 0.004186461132356989,
 0.004997321533922516,
 0.0018410662047338988,
 0.0029024215265347486,
 0.0,
 0.00781715870281241,
 0.0,
 0.0081427545933912,
 0.005059846870043572,
 0.007485975750028295,
 0.002293643282962332,
 0.0014334809978118201,
 0.011752647566766417,
 0.0029203767558678706,
 0.0,
 0.0,
 0.009150394200254208,
 0.0003786722606573534,
 0.0005409478046187743,
 0.0,
 0.0,
 0.007664899055908059,
 0.004356709135946879,
 0.007261572941943406,
 0.007401526361098032,
 0.0035183613755984666,
 0.0,
 0.0,
 0.00399963859056518,
 0.0079198891171548,
 0.002749062452844342,
 0.0,
 0.0,
 0.002737143628989358,
 0.0013674854631129385,
 0.0011797564850914988,
 0.003787354902925699,
 0.007106165506894246,
 0.009346370119257319,
 0.0,
 0.0,
 0.020596443359385486,
 0.0,
 0.005594033447899438,
 0.001675136682181222,
 0.002910134798585151,
 0.010616320884124786,
 0.0008196884715547803,
 0.0007051427810429445,
 0.012554875776324526,
 0.0,
 0.001486821107263392,
 0.005340099947411137,
 0.0,
 0.004127630623175005,
 0.0,
 0.00022636736766612486,
 0.01003765017361724,
 0.00044380544165534275,
 0.004685408623115617,
 0.0,
 0.005942342869678097,
 0.0058001809168577445,
 0.02300005486479728,
 0.00946815619141983,
 0.012011730867888648,
 0.004365239312547953,
 0.0022357304863298566,
 0.0,
 0.0,
 0.0039173295498038385,
 0.0,
 0.0,
 0.0033226264553074536,
 0.0,
 0.006999672373020349,
 0.0,
 0.003016270751636352,
 0.002656777829004753,
 0.011710097600394764,
 0.0,
 0.0,
 0.0,
 0.020671693708120387,
 0.003105542634850522,
 0.0,
 0.0046975616151958555,
 0.0002926067501696217,
 0.00488101975059152,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0059922493170003754,
 0.007424625653529748,
 0.0006077405564393068,
 0.008713085455906544,
 0.0,
 0.05905524507404003,
 0.00781768759034529,
 0.0024950078169823087,
 0.009124011678817823,
 0.004834604788503505,
 0.002593984805522087,
 0.011915267410454344,
 0.005405900720432122,
 0.011077941926386448,
 0.01588990658859668,
 0.017348530176026777,
 0.010642408164127648,
 7.569594240308675e-05,
 0.00477742001256809,
 0.025987539188541575,
 0.00015168954632915899,
 0.006781728394281039,
 0.0,
 0.0053192102173351685,
 0.005611569452805387,
 0.007211643712536908,
 0.003980197824334564,
 0.015030729695181932,
 0.0,
 0.002579501725364697,
 0.007812164269712429,
 0.0,
 0.0013277927055206362,
 0.04290220061590588,
 0.014304193363793516,
 0.0033482797598001213,
 0.001608358312450875,
 0.0,
 0.0,
 0.001620361696680117,
 0.0,
 0.005719251374177059,
 0.0,
 0.0006793901704433836,
 0.002776437520424224,
 0.011208171733888772,
 0.006942835842754125,
 0.007653759472006083,
 0.001322334214075127,
 0.006237513819513207,
 0.008527329350289214,
 0.006241489014390034,
 0.0019434638981072894,
 0.0013087687292161476,
 0.0070331625168007506,
 0.007363881460094035,
 0.0014870684682657398,
 0.005300603222677669,
 0.005254240745520722,
 0.004055857652615291,
 0.009415364186133868,
 0.0004041678245512159,
 0.0019324481014462158,
 0.013277989656400369,
 0.0,
 0.009367510658192746,
 0.0,
 0.0,
 0.0018630334900557877,
 0.0040597733396881,
 0.0005727710251526297,
 0.00823016025048906,
 0.0,
 0.0010493934906534719,
 0.0,
 0.006925558917731056,
 0.005684340664911858,
 0.0016569081010433528,
 0.0,
 0.002944813691313719,
 0.0016123299540153901,
 0.0,
 0.011416189017712242,
 0.0,
 0.0007292038193020822,
 0.0025603676644481155,
 0.001683217585017438,
 0.003800798933951466,
 0.02396815972789046,
 0.009240122639421422,
 0.026967668799646738,
 0.0,
 0.0,
 0.008168545560108154,
 0.0,
 0.002919151739252168,
 0.007911456381108017,
 0.0009937274033320342,
 0.015956512931821543,
 0.007544737739658913,
 0.0,
 0.00837371401229392,
 0.0,
 0.00733968561568199,
 0.002766866657031297,
 0.004735540223121948,
 0.009350527665107577,
 0.0,
 0.0,
 0.0007612094019799898,
 0.013384010334480223,
 0.0027563102839942566,
 0.009328919114135026,
 0.000607570634659993,
 0.0003719390371936804,
 0.001352789700623802,
 0.0,
 0.0,
 0.0031805682188967843,
 0.0,
 0.0029826263131833564,
 0.004167332543406399,
 0.0035833985179856143,
 0.0,
 0.013846931862358414,
 0.0015366072826559218,
 0.0,
 0.00557788801248682,
 0.0075900490679639,
 0.019807808112676017,
 0.0013081815910114258,
 0.000992073588429676,
 0.0,
 0.0,
 0.00795015532114629,
 0.0037546660469947035,
 0.0,
 0.006294079825054588,
 0.010897329426850177,
 0.0010126961925540634,
 0.0,
 0.0058419663088633556,
 0.0,
 0.0010091296846992392,
 0.004779677843206098,
 0.0029785137246309823,
 0.00496593756218866,
 0.012075559678686787,
 0.0015658126177497955,
 0.0,
 0.009468749160711276,
 0.0004983303914949389,
 0.0,
 0.00037060114547760037,
 0.0,
 0.0,
 0.0,
 0.007413594721947359,
 0.0,
 0.0046542788964965,
 0.0005475590752661574,
 0.006491592719520156,
 0.011873335074842117,
 0.003359020726750206,
 0.0,
 0.006219998369730639,
 0.008168558867764464,
 0.0010556394284293447,
 0.0,
 0.00824146872572662,
 0.0017584243789436904,
 0.006060335331031563,
 0.007761371380817117,
 0.00038036133247709714,
 0.0,
 0.0034345853516715152,
 0.02507868206461028,
 0.0,
 0.010072063827012645,
 0.0,
 0.004232852413554866,
 0.014830436836588134,
 0.0005475246575303849,
 0.0017372494734075872,
 0.011143223895709653,
 0.0028419384736309006,
 0.0,
 0.0023318698112118064,
 0.001987214295466,
 0.003280690321834978,
 0.0,
 0.004466586169221909,
 0.0039428435670236794,
 0.0,
 0.0011649231070745003,
 0.00010981791838382549,
 0.009273087852005535,
 0.0,
 0.00818511812558853,
 0.0030808092827374622,
 0.0,
 0.0009161304816909244,
 0.0,
 0.0,
 0.0039766233827207564,
 0.0,
 0.0,
 0.0,
 0.0041809058049024905,
 0.005454784943112578,
 0.0,
 0.013461240324359025,
 0.0011972965984203832,
 0.009051919216688908,
 0.004719402997605648,
 0.0,
 0.0049018803190685745,
 0.004081088073015771,
 0.006304585193239287,
 0.003926833202331892,
 0.005626605861795753,
 0.00020496734932118343,
 0.005691576137905496,
 0.0024803760118956575,
 0.001634869824429952,
 0.0013841062297572648,
 0.0054353975547591915,
 0.006701489357602508,
 0.011587596586020155,
 0.001996188379087105,
 0.0034916744833246582,
 0.009444165718675013,
 0.0014831398708854415,
 0.006683429964537524,
 0.00568313983106572,
 0.00857173865463956,
 0.009026757195248258,
 0.0,
 0.0011733375433058413,
 0.001450382674713424,
 0.0027447588309494897,
 7.78787769712963e-05,
 0.021078516447366358,
 0.018722761547661282,
 0.0004435313345991787,
 0.0013774870741798395,
 0.003089734663748178,
 0.006079056272042305,
 0.0036417394898906608,
 0.005380086647682081,
 0.006838081946211716,
 0.0050169343113064535,
 0.005930750332220569,
 0.0,
 0.00015395086906400124,
 0.0061776241152307065,
 0.005170372919914179,
 0.008042621918905368,
 0.0,
 0.004166785587774502,
 0.0,
 0.005888606396661,
 0.004569873971428162,
 0.0006881509909133499,
 0.007889283887402954,
 0.007854544514425577,
 0.010260073161672878,
 0.0,
 0.10647937643611316,
 0.03279599446468451,
 0.010496478303676948,
 0.0,
 0.004853613693625913,
 0.0006231977331920824,
 0.0018704001152709537,
 0.0,
 0.011252952991783083,
 0.002411360364280135,
 0.003901799011123863,
 0.0,
 0.005084848439745215,
 0.007507327399721042,
 0.0030956743644203755,
 0.0020092837897500715,
 0.009089631707280166,
 0.01559836918807278,
 0.003553811962859754,
 0.0,
 0.0035699618504798636,
 0.0030103471171933904,
 0.001612852811490928,
 0.0006777081483866354,
 0.0010462197004184048,
 0.0011521743148588115,
 0.0,
 0.0,
 0.00023304115210853737,
 0.0035261717889505384,
 0.0,
 0.0019766743681652876,
 0.0,
 0.0053513521479073844,
 0.0,
 0.0054011045200552665,
 0.0,
 0.002680851964051989,
 0.009913323432402699,
 0.0,
 0.008274114978644498,
 0.0,
 0.0,
 0.004433550800146957,
 0.005222561289293548,
 0.014760323420206944,
 0.00494808611058728,
 0.0,
 0.000615774770074573,
 0.005386601519317136,
 0.0019212846054563748,
 0.0,
 0.0016532454139603914,
 0.005870802329146052,
 0.005183515600373667,
 0.00149115996476068,
 0.002060533948276433,
 0.007678951612438922,
 0.0,
 0.014475856589484248,
 0.00901460201948856,
 0.0012146911672474836,
 0.0,
 0.008019327389522601,
 0.0015593286655084526,
 0.0012962965999250287,
 0.004334498492390537,
 0.0006034704306991934,
 0.008396689278406644,
 0.014654712192609054,
 0.0027249508532340982,
 0.002683235978973908,
 0.01489641249071516,
 0.015681984054357834,
 0.0030198055378654054,
 0.012565892788247712,
 0.0009520340914499492,
 0.0018661904498413762,
 0.0003918227094770188,
 0.0,
 0.005916436474510345,
 0.0018642591982027668,
 0.008347797322461048,
 0.0,
 0.0,
 0.0,
 0.010588961855206414,
 0.005640742668661769,
 0.0,
 0.0021756220984823216,
 0.0008164391461709108,
 0.00828450280939208,
 0.010511448182318972,
 0.003949366397828502,
 6.41445821440989e-05,
 0.004397195171547796,
 0.0033826054186589793,
 0.005104609650643077,
 0.0,
 0.0,
 0.0,
 0.0014350089181007775,
 0.0027041634552906757,
 0.0013786801937860638,
 0.008950453427186478,
 0.00012571547126460914,
 0.0056022151487482574,
 0.007121244432727103,
 0.009637355750810706,
 0.0,
 0.0,
 0.008090156268250048,
 0.004187819731463094,
 0.00419378420548755,
 0.0,
 0.006404961814744592,
 0.0016662038625208098,
 0.004542042578091987,
 0.0,
 0.010557232782211212,
 0.0034460542372878322,
 0.00035182876462602763,
 0.009336184559143756,
 0.001635323167486824,
 0.00477964270593878,
 0.0003636680887812993,
 0.0051881555792929746,
 0.0,
 0.0,
 0.0,
 0.01833624245708032,
 0.001528590206867353,
 0.0,
 0.0024933424092110634,
 0.01280525028438051,
 0.00739341827973794,
 0.0,
 0.004991421721131317,
 0.0,
 0.007853828599294399,
 0.008602063113839264,
 0.0,
 0.014557011039629586,
 0.006889915691805193,
 0.00238000979168973,
 0.0,
 0.0016283950145812298,
 0.006103609748002281,
 0.0,
 0.0,
 0.00854785504682365,
 0.0,
 0.0,
 0.006855728180156007,
 0.004907321370025031,
 0.0,
 4.246927530582312e-05,
 0.0,
 0.007477625102914942,
 0.011580161447733328,
 0.004589441014154705,
 0.0,
 0.0031642694970281937,
 0.008484965350349594,
 0.0035411831952076867,
 0.0,
 0.011857856723159532,
 0.006072538846153552,
 0.0,
 0.0,
 0.0019722504280896835,
 0.007750729858508887,
 0.0003800832868026127,
 0.0011243029353980027,
 0.0032054048965104442,
 0.005626433276151754,
 0.0010223589000109001,
 0.011814221822317172,
 0.0,
 0.004354202379502237,
 0.0,
 0.001751355874709315,
 0.0,
 0.007553612632210438,
 0.0037099017749442353,
 0.008081077340694076,
 0.009930961392989879,
 0.008907411583657154,
 0.004015330683416973,
 0.0013225961539546915,
 0.0050052907586883855,
 0.0,
 0.0,
 0.012930901018467722,
 0.006728623420716673,
 0.0,
 0.0,
 0.0,
 0.0,
 0.008028333265817533,
 0.037262320804183346,
 0.0,
 0.005293658692748782,
 0.0,
 0.004897481046198582,
 0.011690490912925178,
 0.0010077668726138356,
 0.00018602921437915754,
 0.0,
 0.009283029541371945,
 0.001420376389849043,
 0.0,
 0.0,
 0.0,
 0.0,
 0.029884085267829263,
 0.022020673169541816,
 0.0,
 0.006307785223269136,
 0.0,
 0.017522244229689843,
 0.0,
 0.0006170072221234335,
 0.0017623860194895258,
 0.005560674787419284,
 0.0011230990159036836,
 0.0023315725924737407,
 0.0,
 0.0014956872053732972,
 0.0,
 0.00030288870841133075,
 0.0008385333479208334,
 0.019599811993892935,
 0.0002580876195552584,
 0.0011390426852857516,
 0.01244574629238393,
 0.0028283453231283673,
 0.0014459623461542392,
 0.0,
 0.0,
 0.019041721428794567,
 0.0,
 0.0,
 0.00784896890943898,
 0.021955334452725683,
 0.013397212625174237,
 0.0009744682249839265,
 0.002246811317875075,
 0.00459127834192774,
 0.008971916832255733,
 0.003611420395147835,
 0.00015451457955384384,
 0.0031849177688223484,
 0.00787869590003254,
 0.007289110498941209,
 0.00034594637391993643,
 0.0040368016568468335,
 0.0,
 0.008195630254618447,
 0.0053435913171608895,
 0.004105241980103536,
 0.0018749962349304816,
 0.0,
 0.0002099211444419602,
 0.004999441323629394,
 0.0034607597732310147,
 0.004709934101794655,
 0.007282870542347553,
 0.0044144548996736255,
 0.0,
 0.004001676822318334,
 0.0,
 0.005397311063793708,
 0.010342126276032815,
 0.0,
 0.0015755119770668458,
 0.003019047584999157,
 0.0,
 0.0,
 0.0,
 0.007077608163581495,
 0.00887381927401698,
 0.0,
 0.001101607055744136,
 0.002677684702068195,
 0.000987049162847864,
 0.0011504861984841241,
 0.004988406390348921,
 0.0,
 0.0005347351422582136,
 0.0017047240303464939,
 0.003300120393022077,
 0.0,
 0.026284313254067104,
 0.009125705983338506,
 4.9237537988133795e-05,
 0.0,
 0.0044058768559231964,
 0.0005655795857828494,
 0.006001806370399265,
 0.001164357825564899,
 0.0,
 0.004127947879195126,
 0.007616253117217031,
 0.0015348470639637846,
 0.0033871854137768054,
 0.004667901608772063,
 0.01107207810284594,
 0.0019405441182729355,
 0.0002822111669775751,
 0.0,
 0.0,
 0.0033382228334142283,
 0.0,
 0.0,
 0.0,
 0.0012423514254744639,
 0.0,
 0.006436483055223263,
 0.0023323326318647197,
 5.6182277440530726e-05,
 0.010524342679141707,
 0.012034434626508439,
 0.0010859223717183397,
 0.007125072095163887,
 0.002939177115350411,
 0.0034130387527744332,
 0.0,
 0.0022081449432040934,
 0.00418026227436874,
 0.003833296018789234,
 0.0023587003866767375,
 0.007843317263280358,
 0.0,
 0.0,
 0.0028131243056419564,
 0.0037617396334912456,
 0.0,
 0.003059672187400775,
 0.006171382391678026,
 0.0,
 0.004262069571821403,
 0.0019319687317862488,
 0.004946465970892433,
 0.006508996961733349,
 0.011922331986154777,
 0.003980818566478472,
 0.004047814531278338,
 0.010593218286039097,
 0.008883395025295115,
 0.007289999400695191,
 0.005602366492506228,
 0.0,
 0.0005663874523071932,
 0.0,
 0.0,
 0.00031610821204575146,
 0.0030494152437934297,
 0.004925157115298173,
 0.002484807422660662,
 0.002971758510470046,
 0.0,
 0.007484284588110679,
 0.0,
 0.012571282050528154,
 0.0016347174285185062,
 0.004400478454077206,
 0.0,
 0.003364643137434342,
 0.00536729584564366,
 0.04224981751740531,
 0.00908464952710153,
 0.013120110060624857,
 0.009356506394802455,
 0.010900654648005048,
 0.009354291417368987,
 0.0,
 0.0022865207318485403,
 0.004038825643315036,
 0.0017310839366020403,
 0.0,
 0.0,
 0.004465357746398002,
 0.00265032703579271,
 0.010547105787315214,
 0.0,
 0.0,
 0.028868862061397937,
 0.0024141209543708797,
 0.0015680673529994138,
 0.0,
 0.007812986859243143,
 0.0,
 0.011726892877676587,
 0.0,
 0.0002662637043497895,
 0.0005331535107915286,
 0.0013141104154423822,
 0.0022427574776537895,
 0.0028272628913508235,
 0.008120961343458077,
 0.017358126185248235,
 0.0,
 0.007476330162127898,
 0.004804963622239367,
 0.009374180098606022,
 0.0,
 0.0007277588234710919,
 0.0,
 0.0,
 0.010585952937432364,
 0.005691542002657535,
 0.0035223504631063385,
 0.00017088898470873914,
 0.011007084826657909,
 0.0016376073429986704,
 0.0051273280301740165,
 0.008186725734805833,
 0.0012077570135562432,
 0.004310325426069461,
 0.0,
 0.003878916983080405,
 0.016507072248143295,
 0.004261235045656342,
 0.0,
 0.016007204171295975,
 0.008865982014068852,
 0.0049106707657982085,
 0.028930621504527743,
 0.0,
 0.004817597249626715,
 0.004588303670485239,
 0.0013183412727437727,
 0.0030023314377274346,
 0.0025409889661092144,
 0.02072513615414806,
 0.0,
 0.008278686416108627,
 0.0,
 0.0,
 0.012710735876834356,
 0.0007224257080808982,
 0.0,
 0.004025097095225583,
 0.004512394020401711,
 0.03211149509249145,
 0.020179740140793267,
 0.01354982264411353,
 0.009020589826078673,
 0.005346720268276428,
 0.00699962904415008,
 0.01647369232435958,
 0.044128453085575,
 0.02849846705846737,
 0.06164098863948331,
 0.02482749220356295,
 0.02850598371715396,
 0.0017560518870078923,
 0.0222265473956047,
 0.0052472125903415545,
 0.0170164454731343,
 0.00432568426025437,
 0.02473543858408611,
 0.036049389171016966,
 0.036656349855407555,
 0.001029467696378461,
 0.0069268484078950365,
 0.0,
 0.012154849456490258,
 0.0020831872246254157,
 0.0,
 0.003365453637738103,
 0.003116557115606877,
 0.015493856249594984,
 0.0,
 0.00016688513658902338,
 0.006329147228066656,
 0.0026626942592562486,
 0.0029309206326604276,
 0.0,
 0.008170330220236721,
 0.006102546280675192,
 0.0,
 0.012439389281680313,
 0.002707734715415633,
 0.01740927060290076,
 0.008480211892046619,
 0.0,
 0.002208928657785325,
 0.005367598416405883,
 0.005496195741743648,
 0.011774814272830891,
 0.00018262929981283094,
 0.0006792993632260824,
 0.007976270317060052,
 0.00014899892348285704,
 0.0067323646370271994,
 0.0,
 0.004397094169469096,
 0.0,
 0.013298678760165217,
 0.0,
 0.012212509884573564,
 0.00930422166265732,
 0.004807598084680453,
 0.004985062870703327,
 0.0027710025844207564,
 0.001491236918596428,
 0.0,
 2.5634052363443516e-05,
 0.0010348539483575614,
 0.0,
 0.007759682568980519,
 0.0009700427489032215,
 0.0,
 0.0021551319747858955,
 0.0037584837976050167,
 0.0,
 0.0,
 0.0,
 0.0007222135542486185,
 0.009553412331909428,
 0.005724400420446418,
 0.010256817225035686,
 0.0,
 0.013551214205731466,
 0.001352314185440573,
 0.0,
 0.0040214798642832505,
 0.007819843543128702,
 0.0,
 0.0,
 0.015519359362003105,
 0.010377130905054877,
 0.005168227556156424,
 0.006093699113030038,
 0.005708035969806069,
 0.0010344634143479858,
 0.002916323323603809,
 0.0,
 0.0,
 0.0,
 0.0033826157647447452,
 0.0,
 0.0,
 0.0,
 0.01629304681002841,
 0.0045678178198445,
 0.005278630665093598,
 0.003980571390269194,
 0.00412738715048544,
 0.027752296765990003,
 0.005516780669135191,
 0.0,
 0.005304313271248251,
 0.001772063605405716,
 0.009314817301597333,
 0.00019561930430089802,
 0.0,
 0.005784276595925508,
 0.00675747973377927,
 0.0,
 0.0051825018138180745,
 0.013171396229034293,
 0.0047803583284729,
 0.004986531131124572,
 0.009647643290001895,
 0.0,
 0.0033663722391703566,
 0.012038631088159946,
 0.0,
 0.009918729616248179,
 0.0007382770656869653,
 0.0029882932840261667,
 0.004789170016286537,
 0.003931387249161311,
 0.004705366519887733,
 0.0,
 0.006892066664177854,
 0.013389793740580025,
 ...]

In [5]:
result = [list(t) for t in zip(X_mutual_info, features)]
result = pd.DataFrame(result)
result = result.loc[result[0] > 0.008, :]
features = result[1]
features

2          ISG15
4        TNFRSF4
14          RBP7
16      TNFRSF1B
19         HSPB7
          ...
2599         NRK
2623       HMGB3
2624       FATE1
2632     MT-ATP8
2633     MT-ND4L
Name: 1, Length: 500, dtype: object

In [6]:
X = merged_features[features]
X.head()

,ISG15,TNFRSF4,RBP7,TNFRSF1B,HSPB7,TEX46,KDM1A,ID3,FAM110D,FCN3,...,SAT1,TIMP1,TSPYL2,CXorf65,ITM2A,NRK,HMGB3,FATE1,MT-ATP8,MT-ND4L
20149X1_AAACGAACACAAATAG-1,-0.504933,3.572244,1.529704,1.953217,-0.274762,-0.524186,-0.539693,1.412673,1.004996,-0.286519,...,0.159355,-0.952402,-0.496833,-0.404458,0.398760,-0.257892,-0.315425,1.542139,-0.503194,0.259315
20149X1_AAACGAACAGACCTAT-1,-0.504933,-0.163379,1.206803,2.458509,-0.274762,0.671765,-0.539693,1.720588,2.849274,-0.286519,...,1.190641,-0.171034,-0.496833,-0.404458,2.247609,-0.257892,-0.315425,-0.263663,-0.503194,0.521004
20149X1_AAACGCTGTAGGACCA-1,1.843142,-0.163379,2.427735,-0.419188,-0.274762,-0.524186,-0.539693,2.008196,1.517562,-0.286519,...,0.959443,0.780182,-0.496833,-0.404458,2.607996,-0.257892,-0.315425,-0.263663,-0.503194,1.228002
20149X1_AAAGAACCACGTTGGC-1,-0.504933,-0.163379,2.121091,-0.419188,-0.274762,-0.524186,-0.539693,2.894780,3.695195,-0.286519,...,1.299590,0.123595,-0.496833,-0.404458,-0.569285,-0.257892,-0.315425,-0.263663,-0.503194,1.606685
20149X1_AAAGTCCGTGGGATTG-1,-0.504933,-0.163379,-0.466696,-0.419188,-0.274762,1.250135,-0.539693,1.497095,-0.385690,2.568544,...,-0.618291,-0.952402,-0.496833,-0.404458,-0.569285,-0.257892,-0.315425,-0.263663,-0.503194,1.088745

# VIF

In [7]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [8]:
vif = [variance_inflation_factor(X.values, X.columns.get_loc(i)) for i in X.columns]
vif

[1.5651729406234194,
 1.2293437993984593,
 4.073589242588674,
 1.4725408550973167,
 1.801967403119422,
 3.0812359909716123,
 1.1371862206974461,
 3.2895387223878942,
 2.3490656119421716,
 1.8044376571526366,
 3.3144961254235152,
 1.0605780466088668,
 3.099532505251465,
 1.409868510181451,
 1.0754116102213858,
 1.2953179368984802,
 1.4876564467643418,
 1.475085684539324,
 1.9196267719289442,
 1.783929885877731,
 3.6446326493524395,
 1.6407801865156384,
 1.523753514103823,
 1.8791753175737895,
 1.3460226996399123,
 3.0557896584842554,
 2.3840386134754077,
 8.691680109098508,
 1.7425457523808296,
 1.1583475703312014,
 2.8115066390432766,
 1.665011652801968,
 3.3187496405545867,
 3.2771618679240744,
 4.218549392304174,
 3.4413489173237988,
 5.569076357124682,
 1.684264216055343,
 2.3655333862634698,
 1.6084452539109515,
 1.8704041962992253,
 1.0583933770935305,
 1.1323334049634113,
 1.2637682777786896,
 1.3440133883165568,
 6.436289881798811,
 1.1385304665471785,
 3.64524361328947,
 2.1883669855511605,
 1.774877018791715,
 1.7459823195340902,
 2.2054301888725885,
 1.090205946972146,
 1.592878264382165,
 1.7578788759004522,
 1.739641076434222,
 2.1292318643327772,
 1.889779881113437,
 2.833245367970828,
 1.4394245444417035,
 2.130707884720635,
 1.3587029917923243,
 10.45964197202105,
 1.9102239705914987,
 1.5742024565887265,
 1.100914312118972,
 2.0687764593367457,
 2.2149360980902535,
 1.1757750655010237,
 1.1301385484879214,
 1.1866291309494523,
 1.232686272821938,
 1.2620200670118298,
 1.4436392891816767,
 2.754407689484821,
 1.6791697195373414,
 1.5767705479835912,
 2.752466379841219,
 4.668841027557873,
 2.8294013729401906,
 1.2028278835740154,
 1.0787748266549897,
 2.3645818820854076,
 3.0093851504868967,
 2.8290046834972498,
 1.254508499661756,
 1.9178815547883363,
 1.1640314049704037,
 1.1886234385209649,
 1.7634925031606312,
 1.465275006063645,
 2.7125272021801234,
 2.6345373355746027,
 2.9279071635856138,
 1.107742301050596,
 1.7720157989341048,
 1.4419502861829945,
 1.5008840563248138,
 1.1618367783886543,
 2.1499026912459573,
 1.1357190235066033,
 1.4818953212920054,
 3.4514250104689945,
 1.188351749252088,
 2.6730287950430447,
 3.644175786797382,
 1.6906417755841263,
 1.1377854341083609,
 1.4379284130197767,
 1.352789096438599,
 1.2390923339264228,
 1.71156758000104,
 2.5005279103066016,
 1.0598990221123226,
 1.0327537506173619,
 1.2028004419009748,
 2.5632560453127184,
 2.9982506642313487,
 6.3987473730729185,
 1.2379670503383997,
 1.3955249011256705,
 27.381921622517638,
 1.3083592166292122,
 1.6413242894270612,
 1.5210037954500295,
 2.404961049513949,
 1.6282524100131195,
 1.2326165213152458,
 2.035653581378289,
 2.8951130732610406,
 1.1057085903206307,
 1.1791847676527487,
 2.674065222884674,
 2.7343592428030314,
 1.74952914461492,
 2.510845135707777,
 1.570869448193972,
 1.427873532610886,
 1.3427502911724127,
 1.1568598609276974,
 1.5782944615797243,
 3.146350611908037,
 8.105396173253975,
 1.2338005722669216,
 1.2289787870585795,
 1.95300952560977,
 2.3312296309987794,
 1.8994078938324328,
 3.1533427749578626,
 2.5130381258646213,
 3.1181179627672466,
 1.1318666061835585,
 2.722298160211418,
 1.2401127833354317,
 1.4682733089334798,
 1.173566723353113,
 1.2618629797501528,
 1.4343877008030137,
 1.0634000811349047,
 1.138995492815702,
 1.196786644353833,
 16.82986251898811,
 1.360798031395046,
 15.294249391173576,
 1.3343800312577072,
 1.1967884244403921,
 1.233358233817438,
 1.2641575485744578,
 2.221742683738529,
 5.75331831048945,
 1.4612340857722055,
 5.378419752362177,
 1.560450659081777,
 1.8131166418315128,
 1.4042131135258185,
 2.01577471466355,
 1.8312742463218281,
 3.3217823803374205,
 2.88720369095328,
 3.5987705673233243,
 1.8949734474689057,
 1.231141744712533,
 3.2240938166581987,
 3.768345025437786,
 2.985313809783855,
 1.1482582788329803,
 1.6553797680281535,
 1.1259302551488974,
 1.0539687909133149,
 1.6195048619583525,
 1.3155506869507576,
 2.440217774720006,
 1.451855625710001,
 1.30274002236668,
 2.2386843442873934,
 1.5581895720694132,
 4.369532286094542,
 1.611061530600367,
 2.5236717740654,
 1.36674956562461,
 1.8156252860333766,
 1.2391892881105246,
 1.1923428870093882,
 1.3447848047284912,
 2.8793994108678524,
 3.6926246694047062,
 1.7969924021279482,
 1.2994416197977048,
 1.5673426078869577,
 9.713274765173699,
 1.3380394029927904,
 1.1544184619040823,
 1.152589880276496,
 1.6233890341806088,
 1.6084298880782646,
 1.2490355076674542,
 1.246647830652357,
 2.1707312914658927,
 5.517544054963897,
 1.3786683103754358,
 4.06169534817631,
 1.7942260689610101,
 1.5421998485997692,
 2.0329395754213495,
 2.1888807219419917,
 2.1165953599034,
 1.6912712342830833,
 1.8658250847645423,
 2.707539878301152,
 1.0749875159826963,
 1.168182889524335,
 1.7692975240256785,
 2.7868701242609633,
 1.1572985443256796,
 1.1760349999355606,
 1.0320239357679186,
 1.175342111210621,
 1.6936452246845926,
 1.2550750902442669,
 1.10170363972534,
 1.1136568892013319,
 1.4373197223875283,
 1.5602144878570916,
 3.933263708529871,
 1.6025120369162509,
 1.109089354224206,
 2.5234925354517026,
 2.9553999145443206,
 2.0298156669603333,
 13.142946000536408,
 1.1344195211519925,
 1.089452765335424,
 1.1077738309876295,
 2.9243481534018105,
 1.828079772428417,
 3.344241496748301,
 3.2081427484730694,
 1.5693119461500293,
 1.685014141640823,
 2.5315651933227863,
 1.1018844121713065,
 1.0715205917811308,
 1.8836750162262093,
 1.5027707695817256,
 1.6741303632111793,
 1.5944428199661003,
 1.0453530282452927,
 1.824236522911997,
 1.08093898296878,
 1.4221334393294924,
 1.1664947753691421,
 1.735848942037155,
 1.4476628790262112,
 2.455151419523949,
 1.8330628582749058,
 3.28183390495603,
 1.2593105423851332,
 1.9706399531110175,
 1.3399757550565397,
 4.669880874970564,
 1.5207865055128342,
 1.4234507371291762,
 2.2582199579016335,
 1.228228118020823,
 1.5641850007914702,
 3.315360032583578,
 2.1360666314407393,
 1.5733392681223488,
 1.2984882723104407,
 1.0663747773519678,
 1.7270415055451975,
 1.8159775337600192,
 2.3369358709134063,
 2.3953214409297146,
 1.084394836059621,
 1.828110219811919,
 1.5252854270485665,
 2.3916585333376195,
 2.5381895146643156,
 1.8836238021774245,
 3.154957513415573,
 1.3310348213802663,
 5.381720910414311,
 3.5561653040239456,
 2.5349451232138738,
 1.7215835108588522,
 1.2330774538329352,
 4.50570209419119,
 1.2453862060779963,
 1.237423375625299,
 3.5719755150176207,
 1.763041303161473,
 1.7497393317303904,
 1.7309421425671396,
 1.3993326388995033,
 2.37873024177122,
 2.5949847265805426,
 1.994169173931715,
 17.629941581243454,
 1.6076412417761299,
 1.550528593089776,
 1.9419772679894478,
 11.986053589768394,
 3.2677813586697044,
 1.9112219363278995,
 7.595321893582213,
 1.8650134806275722,
 1.0823001587386158,
 3.46019678178185,
 1.410375787827699,
 1.1132845210106506,
 2.3092216874921405,
 1.4009556363488533,
 3.487138863538951,
 2.497871890332531,
 3.386908549826379,
 3.8147251495165704,
 1.6441741083627393,
 2.5717922547322436,
 2.341394054684132,
 1.5813754568574927,
 1.0872314934181233,
 1.0373392400573391,
 1.140689919836344,
 1.1585710480575493,
 3.7576293633029967,
 2.93183051104201,
 2.02702005850517,
 1.3083995419061505,
 3.293100698634781,
 3.0037184062565983,
 1.6217759939684437,
 1.1229538697557946,
 1.195078068551841,
 1.3199299763147796,
 1.2650434137817947,
 1.9805728403102727,
 1.236537363349719,
 2.4711110611331786,
 1.3183838176247862,
 1.2099245936580982,
 1.3799987632599424,
 2.90228293960933,
 1.075298678477007,
 32.63899718302269,
 1.4093882025780478,
 1.2520424212726375,
 1.239487029939094,
 2.3154125928848734,
 3.7771828780146666,
 1.4836832555677308,
 1.0911381519425367,
 1.1843148397284171,
 8.23441808761591,
 8.556504328702866,
 4.148781580400659,
 1.0623336005414514,
 1.7871497669964973,
 1.7574116696972693,
 1.4767330894721251,
 1.7454422195413242,
 1.0478776336211248,
 1.8231372316255208,
 1.374846814095774,
 1.0682719179117846,
 2.93612447724394,
 1.2825207574415327,
 2.2466300870664333,
 2.235125380424368,
 1.0357954563541574,
 3.2127503455035753,
 1.0509894391787253,
 2.528316515069589,
 2.651598341621114,
 1.4744966041249647,
 2.6643874121596025,
 2.2561786349197677,
 3.1698981510847766,
 1.0464837473843573,
 2.6984953027001026,
 1.937712443006909,
 1.9724805229283653,
 1.0489951071713066,
 4.861444452588178,
 1.1019687055075813,
 1.4938628607323021,
 2.6215412436801446,
 1.2068629301662652,
 1.8886288584667943,
 1.673915927691902,
 1.1225312673742733,
 1.9269277257220732,
 1.7083890343388837,
 1.3399729010022694,
 1.8760438790863274,
 1.5601683955851955,
 1.9589899472009709,
 3.2322925546021737,
 2.524801600013072,
 1.321757825369285,
 1.1241708357104059,
 2.369849020310512,
 1.396097235171581,
 3.598312757078227,
 2.1018738178639773,
 1.0617498876328457,
 3.3184150041784477,
 2.517298740332735,
 2.7314066527252368,
 3.0982327796622218,
 1.4558639605501178,
 2.1788748025491627,
 1.24907415993293,
 1.9280892688227618,
 1.89185753006594,
 3.1336727169128906,
 2.0177423769851055,
 1.3561651973028488,
 1.1862936349488151,
 1.1677765270716287,
 3.0138314213283874,
 1.5168808011067212,
 1.1180377863069655,
 2.0215041627824424,
 1.5789921374187448,
 1.56353851178558,
 1.9399997399703741,
 1.0542167615735116,
 2.9811311147162574,
 2.961675861327102,
 1.7855742249193742,
 1.162694352085288,
 1.5984701100622667,
 1.8304849163954202,
 3.386311834562142,
 1.7544345089119129,
 2.477806197306078,
 2.681454310950789,
 2.4712891446996674,
 1.0790271232905964,
 2.057861148098715,
 2.016768550713658,
 1.2356277144770003,
 1.7958171493983073,
 1.1248122672745038,
 2.802955465544507,
 1.4013184053956187,
 1.4745800419105364,
 1.382998702662671,
 1.4777594559500957,
 3.1752046964757352,
 1.0601962973478178,
 1.7697661206315678,
 1.1850033369492425,
 3.6350623504766055,
 3.067888105140834,
 2.4973591271268982,
 1.8768949134116002,
 3.0455644839579445,
 5.924151539306315,
 1.7238181361294727,
 1.4129828369198287,
 2.76699676701284,
 1.9232675468462497,
 2.288505922078169,
 1.6454878802122925,
 1.7904740019875085,
 12.981546266475648,
 1.7395850443701995,
 1.519379146399693,
 1.8825361733618273,
 1.2981100713283071,
 1.190145622925741,
 1.946094924142875,
 2.9465434690754853,
 1.620985256124877,
 1.2355978846960396,
 1.0994793731945256,
 1.3311340831010794,
 1.581983767749064]

In [9]:
result_vif = [list(t) for t in zip(vif, features)]
result_vif = pd.DataFrame(result_vif)
result_vif = result_vif.loc[result_vif[0] > 5, :]
result_vif

             0         1
27    8.691680     TXNIP
36    5.569076     ACKR1
45    6.436290      CD34
62   10.459642    TMSB10
118   6.398747    IGFBP7
121  27.381922   SPARCL1
142   8.105396      CD74
161  16.829863     HLA-E
163  15.294249     HLA-B
169   5.753318   HLA-DRA
171   5.378420  HLA-DRB1
209   9.713275     GNG11
218   5.517544      CAV1
249  13.142946       GSN
302   5.381721      CD59
318  17.629942       VWF
322  11.986054       A2M
325   7.595322       MGP
364  32.638997       B2M
373   8.234418      PRM2
374   8.556504      PRM1
479   5.924152     CLDN5
487  12.981546    TMSB4X

In [10]:
X = X.drop(columns = result_vif[1])
features = list(X.columns)
X.head()

,ISG15,TNFRSF4,RBP7,TNFRSF1B,HSPB7,TEX46,KDM1A,ID3,FAM110D,FCN3,...,SAT1,TIMP1,TSPYL2,CXorf65,ITM2A,NRK,HMGB3,FATE1,MT-ATP8,MT-ND4L
20149X1_AAACGAACACAAATAG-1,-0.504933,3.572244,1.529704,1.953217,-0.274762,-0.524186,-0.539693,1.412673,1.004996,-0.286519,...,0.159355,-0.952402,-0.496833,-0.404458,0.398760,-0.257892,-0.315425,1.542139,-0.503194,0.259315
20149X1_AAACGAACAGACCTAT-1,-0.504933,-0.163379,1.206803,2.458509,-0.274762,0.671765,-0.539693,1.720588,2.849274,-0.286519,...,1.190641,-0.171034,-0.496833,-0.404458,2.247609,-0.257892,-0.315425,-0.263663,-0.503194,0.521004
20149X1_AAACGCTGTAGGACCA-1,1.843142,-0.163379,2.427735,-0.419188,-0.274762,-0.524186,-0.539693,2.008196,1.517562,-0.286519,...,0.959443,0.780182,-0.496833,-0.404458,2.607996,-0.257892,-0.315425,-0.263663,-0.503194,1.228002
20149X1_AAAGAACCACGTTGGC-1,-0.504933,-0.163379,2.121091,-0.419188,-0.274762,-0.524186,-0.539693,2.894780,3.695195,-0.286519,...,1.299590,0.123595,-0.496833,-0.404458,-0.569285,-0.257892,-0.315425,-0.263663,-0.503194,1.606685
20149X1_AAAGTCCGTGGGATTG-1,-0.504933,-0.163379,-0.466696,-0.419188,-0.274762,1.250135,-0.539693,1.497095,-0.385690,2.568544,...,-0.618291,-0.952402,-0.496833,-0.404458,-0.569285,-0.257892,-0.315425,-0.263663,-0.503194,1.088745

In [11]:
vif = [variance_inflation_factor(X.values, X.columns.get_loc(i)) for i in X.columns]
result_vif = [list(t) for t in zip(vif, features)]
result_vif = pd.DataFrame(result_vif)
result_vif = result_vif.loc[result_vif[0] > 5, :]
result_vif

Empty DataFrame
Columns: [0, 1]
Index: []

# merge

In [12]:
merged_features_vif = pd.concat([X,y],axis=1) 
merged_features_vif

,ISG15,TNFRSF4,RBP7,TNFRSF1B,HSPB7,TEX46,KDM1A,ID3,FAM110D,FCN3,...,TIMP1,TSPYL2,CXorf65,ITM2A,NRK,HMGB3,FATE1,MT-ATP8,MT-ND4L,age
20149X1_AAACGAACACAAATAG-1,-0.504933,3.572244,1.529704,1.953217,-0.274762,-0.524186,-0.539693,1.412673,1.004996,-0.286519,...,-0.952402,-0.496833,-0.404458,0.398760,-0.257892,-0.315425,1.542139,-0.503194,0.259315,1
20149X1_AAACGAACAGACCTAT-1,-0.504933,-0.163379,1.206803,2.458509,-0.274762,0.671765,-0.539693,1.720588,2.849274,-0.286519,...,-0.171034,-0.496833,-0.404458,2.247609,-0.257892,-0.315425,-0.263663,-0.503194,0.521004,1
20149X1_AAACGCTGTAGGACCA-1,1.843142,-0.163379,2.427735,-0.419188,-0.274762,-0.524186,-0.539693,2.008196,1.517562,-0.286519,...,0.780182,-0.496833,-0.404458,2.607996,-0.257892,-0.315425,-0.263663,-0.503194,1.228002,1
20149X1_AAAGAACCACGTTGGC-1,-0.504933,-0.163379,2.121091,-0.419188,-0.274762,-0.524186,-0.539693,2.894780,3.695195,-0.286519,...,0.123595,-0.496833,-0.404458,-0.569285,-0.257892,-0.315425,-0.263663,-0.503194,1.606685,1
20149X1_AAAGTCCGTGGGATTG-1,-0.504933,-0.163379,-0.466696,-0.419188,-0.274762,1.250135,-0.539693,1.497095,-0.385690,2.568544,...,-0.952402,-0.496833,-0.404458,-0.569285,-0.257892,-0.315425,-0.263663,-0.503194,1.088745,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Older8.TTTACTGTCCACTTCG.1,-0.504933,-0.163379,1.108551,1.719075,-0.274762,-0.524186,1.188605,2.200040,1.575264,1.863989,...,0.335139,-0.496833,-0.404458,0.286136,-0.257892,-0.315425,-0.263663,-0.503194,-0.275360,4
Older8.TTTAGTCCACTAGGTT.1,-0.504933,4.813121,1.956602,-0.419188,-0.274762,-0.524186,1.093138,-0.527442,-0.385690,-0.286519,...,-0.952402,-0.496833,-0.404458,-0.569285,-0.257892,-0.315425,-0.263663,1.224454,0.076884,4
Older8.TTTATGCGTCCGGTGT.1,2.896645,-0.163379,0.901966,0.694665,-0.274762,-0.524186,-0.539693,2.092498,1.290188,1.551356,...,-0.497553,-0.496833,-0.404458,1.199273,-0.257892,-0.315425,-0.263663,-0.503194,1.048292,4
Older8.TTTCAGTAGAGGGTCT.1,-0.504933,-0.163379,-0.466696,2.780469,-0.274762,-0.524186,-0.539693,-0.527442,-0.385690,-0.286519,...,0.836354,-0.496833,-0.404458,-0.569285,-0.257892,-0.315425,-0.263663,2.233176,-0.969345,4
Older8.TTTCGATCATCATTGG.1,-0.504933,-0.163379,1.007062,-0.419188,-0.274762,-0.524186,-0.539693,1.318281,1.938394,3.357177,...,0.814249,-0.496833,-0.404458,2.192468,-0.257892,-0.315425,-0.263663,-0.503194,0.906967,4

In [13]:
merged_features_vif.to_csv("../TPC_info_0.008_vif_5.csv")